### ISSUE TITLE
_sync:local update at remote though replication failed

### ISSUE THREAD

**Issue by ArihantRk** [couchbaselabs/sg-replicate#35] opened 2016-06-08 07:37 UTC
I have setup with 1 syncgateway and 2 CBnodes cluster at source and 1 sync and 1 cbnode cluster.
sg-replication active-active
I would see that , whenever one of cb node failed at source, sg-replicate is failed to replicate some docs. but )sync:local document is updated at the remote cluster which is used for reference for replication.

is there any synchronization between docs insert or doc bulk fetch at source side and update the checkpoint(_sync:local)
what is the rollback mechanism for missed documents at remote.

**Comment by tleyden** [comment] 2016-06-08 17:34
> whenever one of cb node failed at source

Can you give more detail on this?  For example, to reproduce this problem, could the machine running the cb node be shutdown?

> sg-replicate is failed to replicate some docs

Can you give more details on this? 

> is there any synchronization between docs insert or doc bulk fetch at source side and update the checkpoint(_sync:local)

Yes it will only update the checkpoint with the latest sequence of the doc that has been pushed.  

> what is the rollback mechanism for missed documents at remote.

Not sure I understand what you're asking exactly, can you spell this out more?

I think the most important thing here is for us to get the steps to reproduce this so we can study it.  Does it reproduce every time for you?

**Comment by tleyden** [comment] 2016-06-08 17:39
Steps to reproduce:

- Create SyncGatewaySource that is backed CouchbaseClusterSource that has two nodes, with a replica count of 1 (@ArihantRk can you verify the replica count settings you are using?)
- Create SyncGatewayTarget that is backed by CouchbaseClusterTarget that has one node
- Add 10K docs to SyncGatewaySource
- Kick off replication from SyncGatewaySource -> SyncGatewayTarget
- During replication, shutdown one of the nodes in CouchbaseClusterSource by abruptly shutting down the machine where it's running  (@ArihantRk can you verify this is how you are testing?)

**Expected** All 10k docs should be replicated
**Actual** Less than 10k docs are replicated

Does this look correct to you?  Please make any corrections

**Comment by tleyden** [comment] 2016-06-08 19:20
@ArihantRk this may be the cause: https://github.com/couchbase/sync_gateway/issues/1846

Can you reproduce the problem and use a network sniffer utility such as Wireshark, tcpdump, or ngrep, or whatever you can to capture the HTTP traffic between the two sync gateway instances?  Do you see any failed docs in the response to the `bulk_docs` endpoint?

**Comment by ArihantRk** [comment] 2016-06-09 06:16
@tleyden ,

Steps to reproduce,

1. Create SyncGatewaySource that is backed CouchbaseClusterSource that has two nodes, with a replica count of 1
2. Create SyncGatewayTarget that is backed by CouchbaseClusterTarget that has one node
3. Kickoff the replication
4. Add some documents with multiple threads at souce suncgateway cluster, make one of couchbase node down at source. yes down the node while insertion is running.

I had seen below bahavior
1. some documents failed to insert at source and some documents are inserted without sequencenumber and recent_sequence=0. This issue related to syncgateway and has already been raised and fixed in master. Need to test.
2. i could see failed docs  bulk_docs at replication
3. And also _sync:local document at destination has been updated to latest, no action taken here even though bulk_docs partially failed. there will be mismatch in source and destination.


There is no mechanism to sync back if _sync:local documents updated without replication succeeded .

**Comment by tleyden** [comment] 2016-06-21 18:28
@ArihantRk I believe the root cause is https://github.com/couchbase/sync_gateway/issues/1846, which has recently been fixed on the master branch.

I'm going to close this bug, but please try to reproduce using commit https://github.com/couchbase/sync_gateway/commit/83e495a5713d6a0817b146eb26586811096cce6a or later, and re-open this bug if you are still seeing an issue.

**Closed by tleyden** 2016-06-21 18:28 UTC
